#!/bin/bash
script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
cd "$script_dir" || exit 1
git clean -fdx

ymc_path="$HOME/.vim/pack/plugins/bundle-available-github/YouCompleteMe"

ln -s "$ymc_path/third_party/ycmd/"*.so* .
ln -s "$ymc_path/third_party/ycmd/third_party/clang/lib/"*.so* .
